_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 105
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
beam_size:
    value: 1
cell_type:
    value: lstm
decoder_layers:
    value: 2
dropout:
    value: 0.2
embedding_dim:
    value: 16
encoder_layers:
    value: 2
hidden_size:
    value: 64
learning_rate:
    value: 0.0005
pad_idx:
    value: 0
src_vocab_size:
    value: 65
teacher_forcing_ratio:
    value: 0.5
tgt_vocab_size:
    value: 30
