wandb_version: 1

cell_type:
  value: gru
decoder_layers:
  value: 1
dropout:
  value: 0.3
embedding_dim:
  value: 16
encoder_layers:
  value: 1
hidden_size:
  value: 64
learning_rate:
  value: 0.0005
