wandb_version: 1

cell_type:
  value: lstm
decoder_layers:
  value: 1
dropout:
  value: 0.3
embedding_dim:
  value: 32
encoder_layers:
  value: 2
hidden_size:
  value: 256
learning_rate:
  value: 0.0005
