wandb_version: 1

cell_type:
  value: lstm
decoder_layers:
  value: 2
dropout:
  value: 0.2
embedding_dim:
  value: 16
encoder_layers:
  value: 2
hidden_size:
  value: 64
learning_rate:
  value: 0.0005
